PREFIX schema: <http://schema.org/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX myonto: <http://myonto.org/myonto_schema/>

SELECT DISTINCT ?localBook ?name ?isbn10 ?isbn13  ?googleBookLink ?category ?thumbnail WHERE {
	?localBook myonto:hasIsbn10 ?isbn10.
	?localBook myonto:hasIsbn13 ?isbn13.

	FILTER(?isbn10 == ?serviceIsbn10 || ?isbn13 == ?serviceIsbn13).

    	SERVICE <http://localhost/service/googleBooks/getBookByKeyword?keyword=0439554896> {
       		?serviceBook myonto:hasIsbn10 ?serviceIsbn10.
        		?serviceBook myonto:hasIsbn13 ?serviceIsbn13.
		?serviceBook myonto:googleBookLink ?googleBookLink.
		?serviceBook myonto:hasCategory ?category.
		?serviceBook myonto:name ?name.
		?serviceBook myonto:imageLink ?thumbnail.
		#?serviceBook rdf:type ?type.
   	}
}

ORDER BY ?localBook
LIMIT 1