@prefix myonto: <http://myonto.org/>
CONSTRUCT {
    ?bookUri a myonto:Book;
        myonto:name ?title;
        myonto:hasPublisher ?publisher;
        myonto:description ?description;
        myonto:publishedDate ?publishedDate;
        myonto:language ?language;
        myonto:isbn ?isbn;
        myonto:hasPrintType ?printType;
        myonto:hasCategory ?categories;
        myonto:hasAuthor ?authorUri.

    ?authorUri a myonto:Author;
        myonto:name ?author.

} WHERE {   
    ?book

        api:volumeInfo [api:title ?title];
        api:volumeInfo [api:authors ?author];
        #api:volumeInfo [api:description ?description];
        api:volumeInfo [api:industryIdentifiers [api:identifier ?isbn13]];
        api:volumeInfo [api:printType ?printType];
        api:volumeInfo [api:categories ?categories];
        api:volumeInfo [api:publishedDate ?publishedDate];
        api:volumeInfo [api:language ?language];
        api:id ?id;
        api:volumeInfo [api:publisher ?publisher].

    # customize
    bind (IRI(concat("http://localhost/ld/googleBooks/book/", ?id)) AS ?bookUri )
    bind (IRI(concat("http://localhost/ld/googleBooks/author/", ?id)) AS ?authorUri )
}
