@prefix myonto: <http://myonto.org/myonto_schema/> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .

CONSTRUCT {
    ?bookUri a ?publicationType;
        myonto:name ?title;
        myonto:hasPublisher ?publisher;
        myonto:description ?description;
        myonto:publishedDate ?publishedDate;
        myonto:language ?language;
        myonto:hasIsbn10 ?isbn10;
        myonto:hasIsbn13 ?isbn13;
        #myonto:hasPrintType ?printTypeUri;
        myonto:hasCategory ?categories;
        myonto:googleBookLink ?googleBookLink;
        myonto:hasAuthor ?author.

    ?authorUri a myonto:Author;
        myonto:name ?author.

} WHERE {   
    ?book

        api:volumeInfo [api:title ?title];
        api:volumeInfo [api:authors ?author];
        #api:volumeInfo [api:description ?description];
        api:volumeInfo [api:industryIdentifiers [api:identifier ?isbn; api:type ?isbnType]];
        api:volumeInfo [api:printType ?printType];
        api:volumeInfo [api:categories ?categories];
        api:volumeInfo [api:publishedDate ?publishedDate];
        api:volumeInfo [api:language ?language];
        api:volumeInfo [api:infoLink ?googleBookLink];
        api:id ?id;
        api:volumeInfo [api:publisher ?publisher].

    # customize
    bind (IRI(concat("http://localhost/ld/googleBooks/book/", ?id)) AS ?bookUri )
    bind (IRI(concat("http://localhost/ld/googleBooks/author/", ?id)) AS ?authorUri )

    # Determine the print type URI based on the string value of printType
    BIND (IF(?printType = "BOOK", myonto:Book, 
           myonto:Magazine) AS ?publicationType)

    # ISBN Handling
    BIND (IF(?isbnType = "ISBN_10", ?isbn, "") AS ?isbn10)
    BIND (IF(?isbnType = "ISBN_13", ?isbn, "") AS ?isbn13)
}
